# Generated by Django 6.0.5 on 2026-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='यह इमेज सीधे Supabase Storage में जाएगी', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='अपनी .mp4 वीडियो फाइल यहाँ अपलोड करें (Supabase Storage)', null=True, upload_to='videos/'),
        ),
    ]
